dist: trusty
language: python
python:
  - "3.6" # 3.6 development branch

addons:
  apt:
    packages:
    - binutils
    - libproj-dev
    - gdal-bin
    - libgeoip1
    - python-gdal
    - spatialite-bin


install:
  - "pip install -r requirements.txt"
  - "pip install codecov"
  - "pip install coverage"
  - npm install -g bower

before_script:
  - python manage.py bower install
  - python manage.py migrate

# command to run tests
script:
  - coverage run python3 manage.py test
  - coverage run python3 manage.py test functional_tests



after_success:
  - codecov