dist: trusty
language: python
python:
  - "3.5" # Debian 9 use python 3.5, and we use debian 9 on our server

addons:
  apt:
    packages:
    - binutils
    - libproj-dev
    - gdal-bin
    - libgeoip1
    - python-gdal
    - spatialite-bin


install:
  - "pip install -r requirements.txt"
  - "pip install codecov"
  - "pip install coverage"

before_script:
  - python manage.py migrate --no-input

# command to run tests
script:
  - ALL_TESTS=1 coverage run manage.py test

after_success:
  - codecov