# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevEUI', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Invalide EID-64. Use only 16 caps between A-F and digits. ', regex='^[A-F|\\d]{16}$')])),
                ('name', models.TextField()),
            ],
        ),
    ]
