# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
