# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0002_device_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
