# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0003_auto_20170505_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('E', 'ERROR'), ('W', 'WARNING'), ('O', 'OK')], default='E', max_length=1),
            preserve_default=False,
        ),
    ]
